service: puppeteer-ts-script

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 512
  timeout: 30

functions:
  puppeteer:
    handler: dist/handler.handler

plugins:
  - serverless-offline