service: puppeteer-ts-script

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  memorySize: 512
  timeout: 30

functions:
  puppeteer:
    handler: dist/handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:puppeteer-queue
          batchSize: 1
          enabled: true

resources:
  Resources:
    PuppeteerQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: puppeteer-queue


plugins:
  - serverless-offline
  - serverless-offline-sqs

custom:
  serverless-offline-sqs:
    endpoint: http://localhost:9324
    region: us-east-1
    accessKeyId: test
    secretAccessKey: test
    autoCreate: true
    skipCacheInvalidation: true